### ISSUE TITLE
Добавление группы в группу

### ISSUE THREAD

**Issue by ivanbibik** [antirek/network-diagram#17]
Добрый день,
рассмотрите возможность добавления группы в группу, допустим необходимо в группу "офис" добавить группы "кабинет 1", "кабинет 2", ... "Кабинет N"

**Comment by antirek** [comment]
привет, рассматривал такой вариант на момент реализации, но проще лучше. поэтому вариант с одним уровнем группировки. сейчас проектом только пользуюсь, не развиваю его. 
можете воспользоваться оригинальным проектом cytoscape.js и реализовать на свой вкус

**Comment by ivanbibik** [comment]
Привет,
из коробки работает) добавил parent объекту group и взлетело)
спасибо
